version: '2.2'
services:
  miner:
    build: .
    image: valentinvieriu/docker-xmr-stack-cpu:v1.3.0-1.5.0
    container_name: xmr-miner
    cpuset: '0,2,4,6'
    privileged: true
    environment:
      WALLET_ADDRESS: ${WALLET_ADDRESS}
      POOL_ADDRESS: ${POOL_ADDRESS}
      POOL_PASSWORD: ${POOL_PASSWORD}
      HTTPD_PORT: 9999
      CORES: 4
      # AUTO_THREAD_CONFIG: ${AUTO_THREAD_CONFIG}
      # THREAD_CONFIG: ${THREAD_CONFIG}
    # entrypoint: "/bin/sh -c"
    ports: 
      - 9999:9999
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always